name: service_locator
description: A starting point for Dart libraries or applications.
version: 0.1.0
repository: https://github.com/abitofevrything/service_locator

environment:
  sdk: ^2.17.0

dependencies:
  # For the compatibility layer, otherwise unused.
  get_it: ^7.2.0
  runtime_type: ^1.0.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
